parameters:
- name: environment
  displayName: Environment to build
  type: string
  default: dev
  values: [dev, stg, prod]

variables:
- group: ${{ format('var-group-{0}', parameters.environment) }} # dynamic variable group name
- name: buildContextPath
  value: 'docker-demo/src'
- name: tag
  value: '$(Build.BuildId)'

trigger: none
  # branches:
  #   include:
  #     - main

pool:
  vmImage: 'ubuntu-latest'

# variables:
#   dockerRegistryServiceConnection: 'HaoACRConn'
#   buildContextPath: 'docker-demo/src'
#   tag: '$(Build.BuildId)'


stages:
- stage: CIStage
  displayName: CI stage

  jobs:
  - job: BuildAndPush
    displayName: Build & Push Image

    steps:
    - checkout: self
      displayName: 'Checkout source code'

    # - task: Docker@2
    #   displayName: 'Login to ACR'
    #   inputs:
    #     command: 'login'
    #     containerRegistry: '$(dockerRegistryServiceConnection)'

    # - task: Docker@2
    #   displayName: 'Build and Push backend image to ACR'
    #   inputs:
    #     containerRegistry: '$(dockerRegistryServiceConnection)'
    #     repository: 'backend'
    #     command: 'buildAndPush'
    #     Dockerfile: '$(buildContextPath)/backend/Dockerfile'
    #     buildContext: '$(buildContextPath)/backend'
    #     tags: |
    #       $(tag)
    #       latest

    # - task: Docker@2
    #   displayName: 'Build and Push Frontend image to ACR'
    #   inputs:
    #     containerRegistry: '$(dockerRegistryServiceConnection)'
    #     repository: 'frontend'
    #     command: 'buildAndPush'
    #     Dockerfile: '$(buildContextPath)/frontend/Dockerfile'
    #     buildContext: '$(buildContextPath)/frontend'
    #     tags: |
    #       $(tag)
    #       latest

    - task: AzureCLI@2
      displayName: Login to Azure and ACR
      inputs:
        azureSubscription: '$(AZURE_SUBSCRIPTOIN_SERVICE_CONNECTION)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Logging into ACR..."
          az acr login --name $(ACR_NAME)

    - task: Bash@3
      displayName: Build and push Docker image for backend
      inputs:
        targetType: 'inline'
        script: |
          echo "Building backend Docker image..."
          cd $(buildContextPath)
          docker build ./backend -t $(ACR_NAME).azurecr.io/backend:$(tag)
          docker tag $(ACR_NAME).azurecr.io/backend:$(tag) $(ACR_NAME).azurecr.io/backend:latest

          echo "Pushing backend Docker image to ACR..."
          docker push $(ACR_NAME).azurecr.io/backend:$(Build.BuildId)
          docker push $(ACR_NAME).azurecr.io/backend:latest

    - task: Bash@3
      displayName: Build and push Docker image for frontend
      inputs:
        targetType: 'inline'
        script: |
          echo "Building frontend Docker image..."
          cd $(buildContextPath)
          docker build ./frontend -t $(ACR_NAME).azurecr.io/frontend:$(tag)
          docker tag $(ACR_NAME).azurecr.io/frontend:$(tag) $(ACR_NAME).azurecr.io/frontend:latest

          echo "Pushing frontend Docker image to ACR..."
          docker push $(ACR_NAME).azurecr.io/frontend:$(Build.BuildId)
          docker push $(ACR_NAME).azurecr.io/frontend:latest
